### PR TITLE
allow for mongodb dns connection format

### PR DESCRIPTION
**Pull request by cstryker**

### CODE REVIEW

**Review by dsellarsnr — APPROVED** [review]
Looks good

**Comment by jimmyjayp** [comment]
The mongo+svr notation pulls all the connection components from DNS (hosts, ports, options, etc...). There are places in the code where we construct a URL based on those properties. This change of just pattern matching the +srv won't be sufficient to gather all the connection properties.

**Comment by cstryker** [comment]
@jimmyjayp can you review this update per our conversation earlier?

**Review by jimmyjayp — APPROVED** [review]
LGTM

**Pull request merged**
