### PR TITLE
add webview nr agent props and cleanup onprem_admin removal

### PR DESCRIPTION
**Pull request by jimmyjayp**
**This PR Addresses:**  
[NR-1656 Config support for New Relic ingest](https://issues.newrelic.com/browse/NR-1656)  

<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>

### CODE REVIEW

**Comment by bcanzanella** [comment]
looks good, but allow me wait to approve it to see if we get a response on that agentId vs. applicationId open question.

**Comment by bcanzanella** [comment]
@jimmyjayp i updated the jira card to add the info for the additional agentID prop.

**Comment by jimmyjayp** [comment]
As per Brian, I've added a new property, webviewAgentId to the config.  It's still part of schema version 27 which has been deployed to all environments so it should be safe to merge this branch into develop.

**Comment by bcanzanella** [comment]
looks good, merge when you're rdy.

**Comment by jimmyjayp** [comment]
Sorry - meant to set Brian and Colin up as reviewers, not assignees!

**Review by bcanzanella — APPROVED** [review]

**Pull request merged**
